//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExchangeRule()
        {
            this.ActivityBankDetails = new HashSet<ActivityBankDetail>();
            this.Exchange_Gifts = new HashSet<Exchange_Gifts>();
            this.Exchange_Gifts_Online = new HashSet<Exchange_Gifts_Online>();
            this.ExchangeLimitCreditPeriods = new HashSet<ExchangeLimitCreditPeriod>();
            this.ExchangeMalls = new HashSet<ExchangeMall>();
        }
    
        public int Id { get; set; }
        public string RuleNo { get; set; }
        public Nullable<int> AGId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> LimitPrice { get; set; }
        public Nullable<int> LimitCrdeitPeriods { get; set; }
        public Nullable<int> LimitQuantity { get; set; }
        public Nullable<bool> IsPlus { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsPreOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityBankDetail> ActivityBankDetails { get; set; }
        public virtual ActivityGroup ActivityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Gifts> Exchange_Gifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Gifts_Online> Exchange_Gifts_Online { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeLimitCreditPeriod> ExchangeLimitCreditPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeMall> ExchangeMalls { get; set; }
    }
}
