//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class HGCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HGCertificate()
        {
            this.HGCertificate_Detail = new HashSet<HGCertificate_Detail>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string AGId { get; set; }
        public string MemberId { get; set; }
        public Nullable<long> ExchangeUser { get; set; }
        public string HappyGoNo { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RRN { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> RemainPoint { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string Mode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HGCertificate_Detail> HGCertificate_Detail { get; set; }
    }
}
