//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class LargeCoupon_Log
    {
        public int Id { get; set; }
        public string MallId { get; set; }
        public string NonMemberId { get; set; }
        public Nullable<int> GId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<bool> IsUse { get; set; }
    }
}
