//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberRecord()
        {
            this.MemberGiftsVouchers_Log = new HashSet<MemberGiftsVouchers_Log>();
            this.RecordPayments = new HashSet<RecordPayment>();
        }
    
        public long Id { get; set; }
        public string MemberId { get; set; }
        public string MallId { get; set; }
        public string TransactionNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> IntegralPrice { get; set; }
        public Nullable<decimal> InvoicePrice { get; set; }
        public Nullable<decimal> HappyGoPrice { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNo { get; set; }
        public string HappyGoNo { get; set; }
        public string HGIsRemark { get; set; }
        public string CarBrand { get; set; }
        public string CarToken { get; set; }
        public string Source { get; set; }
        public string PosId { get; set; }
        public string RecordKey { get; set; }
        public Nullable<bool> IsStaff { get; set; }
        public Nullable<bool> IsPreOrder { get; set; }
        public string TaxId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<System.DateTime> CreatOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGiftsVouchers_Log> MemberGiftsVouchers_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordPayment> RecordPayments { get; set; }
    }
}
