//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosIdList
    {
        public long Id { get; set; }
        public string MallId { get; set; }
        public string DepartmentNo { get; set; }
        public string PosId { get; set; }
        public Nullable<long> GId { get; set; }
        public Nullable<long> ERId { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<long> ModifyUser { get; set; }
    }
}
