//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordPayment()
        {
            this.RecordPaymentDetails = new HashSet<RecordPaymentDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> MRId { get; set; }
        public string PayTools { get; set; }
        public string ThirdPayTools { get; set; }
        public string CreditNo { get; set; }
        public Nullable<int> CreditPeriods { get; set; }
        public string CreditToken { get; set; }
    
        public virtual MemberRecord MemberRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordPaymentDetail> RecordPaymentDetails { get; set; }
    }
}
