//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordPaymentDetail
    {
        public long Id { get; set; }
        public Nullable<long> RPId { get; set; }
        public string PayCode { get; set; }
        public Nullable<decimal> PayPrice { get; set; }
        public string PayCheck { get; set; }
    
        public virtual RecordPayment RecordPayment { get; set; }
    }
}
