//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models.Gifts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnGiftsMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnGiftsMain()
        {
            this.ReturnCoupons = new HashSet<ReturnCoupon>();
        }
    
        public int Id { get; set; }
        public string MallId { get; set; }
        public string InvoiceNo { get; set; }
        public string TransactionNo { get; set; }
        public string PosId { get; set; }
        public string Type { get; set; }
        public Nullable<int> GId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string Status { get; set; }
        public Nullable<int> ModifyUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnCoupon> ReturnCoupons { get; set; }
    }
}
