//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponReportUpload_Log
    {
        public long Id { get; set; }
        public string MallId { get; set; }
        public int AId { get; set; }
        public int ERId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ArrangeDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUser { get; set; }
        public string Type { get; set; }
        public bool IsUse { get; set; }
    }
}
