//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditCard()
        {
            this.CreditCard_Log = new HashSet<CreditCard_Log>();
            this.CreditCardCoupons = new HashSet<CreditCardCoupon>();
            this.CreditCardGroups = new HashSet<CreditCardGroup>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AId { get; set; }
        public string MallId { get; set; }
        public string CardNo { get; set; }
        public string ECardNo { get; set; }
        public string MemberId { get; set; }
        public string BankNo { get; set; }
        public string CardType { get; set; }
        public string CardKind { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public System.DateTime CreateOn { get; set; }
        public bool IsUse { get; set; }
        public string Status { get; set; }
        public string CardToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCard_Log> CreditCard_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardCoupon> CreditCardCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardGroup> CreditCardGroups { get; set; }
    }
}
