//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditCardGroup()
        {
            this.CreditCardGifts = new HashSet<CreditCardGift>();
            this.CreditCardGroup_Log = new HashSet<CreditCardGroup_Log>();
            this.CreditCardInvoices = new HashSet<CreditCardInvoice>();
        }
    
        public long Id { get; set; }
        public long CCId { get; set; }
        public string MallId { get; set; }
        public int AGId { get; set; }
        public int ERId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime CreateOn { get; set; }
        public bool IsUse { get; set; }
        public string Status { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardGift> CreditCardGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardGroup_Log> CreditCardGroup_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardInvoice> CreditCardInvoices { get; set; }
    }
}
