//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVourcher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVourcher()
        {
            this.EVourchers_Gifts = new HashSet<EVourchers_Gifts>();
            this.EVourchers_Invoice = new HashSet<EVourchers_Invoice>();
        }
    
        public long Id { get; set; }
        public string MallId { get; set; }
        public string MemberId { get; set; }
        public string BankNo { get; set; }
        public Nullable<long> AGId { get; set; }
        public Nullable<long> ERId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public Nullable<bool> IsUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVourchers_Gifts> EVourchers_Gifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVourchers_Invoice> EVourchers_Invoice { get; set; }
    }
}
