//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeEntity_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExchangeEntity_Log()
        {
            this.ExchangeEntityGifts = new HashSet<ExchangeEntityGift>();
            this.ExchangeEntityHGRecords = new HashSet<ExchangeEntityHGRecord>();
            this.ExchangeEntityInvoices = new HashSet<ExchangeEntityInvoice>();
        }
    
        public long Id { get; set; }
        public string MemberId { get; set; }
        public string GroupId { get; set; }
        public string MallId { get; set; }
        public Nullable<int> AGId { get; set; }
        public Nullable<int> ERId { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string BankNo { get; set; }
        public Nullable<int> ExchangeCount { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> ReturnUser { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeEntityGift> ExchangeEntityGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeEntityHGRecord> ExchangeEntityHGRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeEntityInvoice> ExchangeEntityInvoices { get; set; }
    }
}
