//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeMall
    {
        public int Id { get; set; }
        public Nullable<int> ERId { get; set; }
        public string MallId { get; set; }
        public Nullable<bool> IsUnlimited { get; set; }
        public Nullable<bool> IsDeptContain { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ExchangeStart { get; set; }
        public Nullable<System.DateTime> ExchangeEnd { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsUse { get; set; }
    
        public virtual ExchangeRule ExchangeRule { get; set; }
    }
}
