//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeEntityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExchangeEntityType()
        {
            this.ExchangeEntityBanks = new HashSet<ExchangeEntityBank>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AGId { get; set; }
        public Nullable<int> FId { get; set; }
        public string ControlType { get; set; }
        public string ExchangeLimitType { get; set; }
        public string CardType { get; set; }
        public string ModelType { get; set; }
        public Nullable<bool> IsDept { get; set; }
        public Nullable<int> LimitQuantity { get; set; }
        public Nullable<bool> IsUse { get; set; }
    
        public virtual ActivityGroup ActivityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeEntityBank> ExchangeEntityBanks { get; set; }
        public virtual File File { get; set; }
    }
}
