//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftsEntities : DbContext
    {
        public GiftsEntities()
            : base("name=GiftsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionToken> ActionTokens { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityBank> ActivityBanks { get; set; }
        public virtual DbSet<ActivityBankDetail> ActivityBankDetails { get; set; }
        public virtual DbSet<ActivityCreditCard> ActivityCreditCards { get; set; }
        public virtual DbSet<ActivityCreditCardLimit> ActivityCreditCardLimits { get; set; }
        public virtual DbSet<ActivityGroup> ActivityGroups { get; set; }
        public virtual DbSet<ActivityGroupMall> ActivityGroupMalls { get; set; }
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<Auth_Setting> Auth_Setting { get; set; }
        public virtual DbSet<BankMain> BankMains { get; set; }
        public virtual DbSet<BankMainDetail> BankMainDetails { get; set; }
        public virtual DbSet<BankMainRF> BankMainRFs { get; set; }
        public virtual DbSet<BonusCoupon> BonusCoupons { get; set; }
        public virtual DbSet<BonusCoupon_Log> BonusCoupon_Log { get; set; }
        public virtual DbSet<BonusWallet> BonusWallets { get; set; }
        public virtual DbSet<BonusWallet_Log> BonusWallet_Log { get; set; }
        public virtual DbSet<CalculationCoupon> CalculationCoupons { get; set; }
        public virtual DbSet<CalculationInvoice> CalculationInvoices { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<CardTypeKind> CardTypeKinds { get; set; }
        public virtual DbSet<CarScanInvoice_Log> CarScanInvoice_Log { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Coupon_Log> Coupon_Log { get; set; }
        public virtual DbSet<Coupon_Temporary> Coupon_Temporary { get; set; }
        public virtual DbSet<CouponFillRecord> CouponFillRecords { get; set; }
        public virtual DbSet<CouponImportTask> CouponImportTasks { get; set; }
        public virtual DbSet<CouponPrinting> CouponPrintings { get; set; }
        public virtual DbSet<CouponReportUpload_Log> CouponReportUpload_Log { get; set; }
        public virtual DbSet<CreditCard> CreditCards { get; set; }
        public virtual DbSet<CreditCard_Log> CreditCard_Log { get; set; }
        public virtual DbSet<CreditCardCoupon> CreditCardCoupons { get; set; }
        public virtual DbSet<CreditCardGift> CreditCardGifts { get; set; }
        public virtual DbSet<CreditCardGifts_Log> CreditCardGifts_Log { get; set; }
        public virtual DbSet<CreditCardGiftsVoucher> CreditCardGiftsVouchers { get; set; }
        public virtual DbSet<CreditCardGroup> CreditCardGroups { get; set; }
        public virtual DbSet<CreditCardGroup_Log> CreditCardGroup_Log { get; set; }
        public virtual DbSet<CreditCardInvoice> CreditCardInvoices { get; set; }
        public virtual DbSet<CreditCardLimitDetail> CreditCardLimitDetails { get; set; }
        public virtual DbSet<CreditPeriodsType> CreditPeriodsTypes { get; set; }
        public virtual DbSet<CRMTransferLog> CRMTransferLogs { get; set; }
        public virtual DbSet<Cumulative> Cumulatives { get; set; }
        public virtual DbSet<Cumulative_Log> Cumulative_Log { get; set; }
        public virtual DbSet<Cumulative_Temporary> Cumulative_Temporary { get; set; }
        public virtual DbSet<CumulativeCoupon> CumulativeCoupons { get; set; }
        public virtual DbSet<CumulativeDepartmentSetting> CumulativeDepartmentSettings { get; set; }
        public virtual DbSet<CumulativeDept> CumulativeDepts { get; set; }
        public virtual DbSet<CumulativeDept_Log> CumulativeDept_Log { get; set; }
        public virtual DbSet<CumulativeDeptCoupon> CumulativeDeptCoupons { get; set; }
        public virtual DbSet<CumulativeDeptInvoice> CumulativeDeptInvoices { get; set; }
        public virtual DbSet<CumulativeInvoice> CumulativeInvoices { get; set; }
        public virtual DbSet<CumulativeMain> CumulativeMains { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<EntityCoupon> EntityCoupons { get; set; }
        public virtual DbSet<EntityCoupon_Log> EntityCoupon_Log { get; set; }
        public virtual DbSet<EntityPresent> EntityPresents { get; set; }
        public virtual DbSet<EntityPresent_Log> EntityPresent_Log { get; set; }
        public virtual DbSet<EVourcher> EVourchers { get; set; }
        public virtual DbSet<EVourchers_Gifts> EVourchers_Gifts { get; set; }
        public virtual DbSet<EVourchers_Invoice> EVourchers_Invoice { get; set; }
        public virtual DbSet<EVourchers_Log> EVourchers_Log { get; set; }
        public virtual DbSet<EVourchersCoupon> EVourchersCoupons { get; set; }
        public virtual DbSet<EVourchersCouponMain> EVourchersCouponMains { get; set; }
        public virtual DbSet<EVourchersCouponReturn> EVourchersCouponReturns { get; set; }
        public virtual DbSet<Exchange_Gifts> Exchange_Gifts { get; set; }
        public virtual DbSet<Exchange_Gifts_Online> Exchange_Gifts_Online { get; set; }
        public virtual DbSet<ExchangeBonus_Log> ExchangeBonus_Log { get; set; }
        public virtual DbSet<ExchangeCreditCardLimit> ExchangeCreditCardLimits { get; set; }
        public virtual DbSet<ExchangeCreditCardLimitSetting> ExchangeCreditCardLimitSettings { get; set; }
        public virtual DbSet<ExchangeDepartment> ExchangeDepartments { get; set; }
        public virtual DbSet<ExchangeDepartmentSetting> ExchangeDepartmentSettings { get; set; }
        public virtual DbSet<ExchangedRecord> ExchangedRecords { get; set; }
        public virtual DbSet<ExchangeEntity_Log> ExchangeEntity_Log { get; set; }
        public virtual DbSet<ExchangeEntityBank> ExchangeEntityBanks { get; set; }
        public virtual DbSet<ExchangeEntityGift> ExchangeEntityGifts { get; set; }
        public virtual DbSet<ExchangeEntityHGRecord> ExchangeEntityHGRecords { get; set; }
        public virtual DbSet<ExchangeEntityInvoice> ExchangeEntityInvoices { get; set; }
        public virtual DbSet<ExchangeEntityType> ExchangeEntityTypes { get; set; }
        public virtual DbSet<ExchangeHGLimit> ExchangeHGLimits { get; set; }
        public virtual DbSet<ExchangeInvoice> ExchangeInvoices { get; set; }
        public virtual DbSet<ExchangeLimitCreditPeriod> ExchangeLimitCreditPeriods { get; set; }
        public virtual DbSet<ExchangeLog> ExchangeLogs { get; set; }
        public virtual DbSet<ExchangeMall> ExchangeMalls { get; set; }
        public virtual DbSet<ExchangeMiddleDepartment> ExchangeMiddleDepartments { get; set; }
        public virtual DbSet<ExchangeModelType> ExchangeModelTypes { get; set; }
        public virtual DbSet<ExchangeRecord> ExchangeRecords { get; set; }
        public virtual DbSet<ExchangeRule> ExchangeRules { get; set; }
        public virtual DbSet<ExchangeType> ExchangeTypes { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<GiftsInstruction> GiftsInstructions { get; set; }
        public virtual DbSet<GiftsType> GiftsTypes { get; set; }
        public virtual DbSet<GroupAuth_Main> GroupAuth_Main { get; set; }
        public virtual DbSet<GroupAuth_Setting> GroupAuth_Setting { get; set; }
        public virtual DbSet<GroupClass> GroupClasses { get; set; }
        public virtual DbSet<HGCertificate> HGCertificates { get; set; }
        public virtual DbSet<HGCertificate_Detail> HGCertificate_Detail { get; set; }
        public virtual DbSet<HGMakeUp_Log> HGMakeUp_Log { get; set; }
        public virtual DbSet<HGRecord> HGRecords { get; set; }
        public virtual DbSet<HGRecord_Log> HGRecord_Log { get; set; }
        public virtual DbSet<HGRecordMain> HGRecordMains { get; set; }
        public virtual DbSet<HGResultError> HGResultErrors { get; set; }
        public virtual DbSet<HGResultLog> HGResultLogs { get; set; }
        public virtual DbSet<InvoiceFillRecord> InvoiceFillRecords { get; set; }
        public virtual DbSet<InvoiceRecord> InvoiceRecords { get; set; }
        public virtual DbSet<IVector> IVectors { get; set; }
        public virtual DbSet<LargeCoupon_Log> LargeCoupon_Log { get; set; }
        public virtual DbSet<LimitTypeDetailType> LimitTypeDetailTypes { get; set; }
        public virtual DbSet<LimitTypeType> LimitTypeTypes { get; set; }
        public virtual DbSet<Login_Setting> Login_Setting { get; set; }
        public virtual DbSet<LotteryCoupon> LotteryCoupons { get; set; }
        public virtual DbSet<LotteryCoupon_Log> LotteryCoupon_Log { get; set; }
        public virtual DbSet<MainCategory> MainCategories { get; set; }
        public virtual DbSet<Mall> Malls { get; set; }
        public virtual DbSet<MallType> MallTypes { get; set; }
        public virtual DbSet<MealCoupon> MealCoupons { get; set; }
        public virtual DbSet<MemberDiscountCoupon> MemberDiscountCoupons { get; set; }
        public virtual DbSet<MemberDisountReocrd> MemberDisountReocrds { get; set; }
        public virtual DbSet<MemberGiftsVoucher> MemberGiftsVouchers { get; set; }
        public virtual DbSet<MemberGiftsVouchers_Log> MemberGiftsVouchers_Log { get; set; }
        public virtual DbSet<MemberRecord> MemberRecords { get; set; }
        public virtual DbSet<MemberRecord_AddLog> MemberRecord_AddLog { get; set; }
        public virtual DbSet<MemberRecord_Log> MemberRecord_Log { get; set; }
        public virtual DbSet<MemberToken> MemberTokens { get; set; }
        public virtual DbSet<MiddleCategory> MiddleCategories { get; set; }
        public virtual DbSet<ModelType> ModelTypes { get; set; }
        public virtual DbSet<OfflineCouponUsed> OfflineCouponUseds { get; set; }
        public virtual DbSet<OnlineDiscountRecord> OnlineDiscountRecords { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Page_Auth> Page_Auth { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PointPacket> PointPackets { get; set; }
        public virtual DbSet<PointPacket_Log> PointPacket_Log { get; set; }
        public virtual DbSet<PosIdList> PosIdLists { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<PosToken> PosTokens { get; set; }
        public virtual DbSet<PresentEvent> PresentEvents { get; set; }
        public virtual DbSet<PrintAgain> PrintAgains { get; set; }
        public virtual DbSet<ProductData> ProductDatas { get; set; }
        public virtual DbSet<ReceivePrize> ReceivePrizes { get; set; }
        public virtual DbSet<RecordClassification> RecordClassifications { get; set; }
        public virtual DbSet<RecordPayment> RecordPayments { get; set; }
        public virtual DbSet<RecordPaymentDetail> RecordPaymentDetails { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<RegisterRecordLog> RegisterRecordLogs { get; set; }
        public virtual DbSet<RePrintCoupon> RePrintCoupons { get; set; }
        public virtual DbSet<ReturnCoupon> ReturnCoupons { get; set; }
        public virtual DbSet<ReturnGiftsMain> ReturnGiftsMains { get; set; }
        public virtual DbSet<SAPType> SAPTypes { get; set; }
        public virtual DbSet<Signoff_Main> Signoff_Main { get; set; }
        public virtual DbSet<Signoff_Stage> Signoff_Stage { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<System_Setting> System_Setting { get; set; }
        public virtual DbSet<SystemAuth> SystemAuths { get; set; }
        public virtual DbSet<SystemErrorLog> SystemErrorLogs { get; set; }
        public virtual DbSet<SystemExchangeLog> SystemExchangeLogs { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<SystemMailAlert> SystemMailAlerts { get; set; }
        public virtual DbSet<SystemModifyLog> SystemModifyLogs { get; set; }
        public virtual DbSet<SystemType> SystemTypes { get; set; }
        public virtual DbSet<ThirdPayment> ThirdPayments { get; set; }
        public virtual DbSet<UsedDepartment> UsedDepartments { get; set; }
        public virtual DbSet<UsedDepartmentSetting> UsedDepartmentSettings { get; set; }
        public virtual DbSet<UsedMiddleDepartment> UsedMiddleDepartments { get; set; }
        public virtual DbSet<UsedRecord> UsedRecords { get; set; }
        public virtual DbSet<UsedRule> UsedRules { get; set; }
        public virtual DbSet<UserInfo_Main> UserInfo_Main { get; set; }
        public virtual DbSet<UserInfo_Setting> UserInfo_Setting { get; set; }
        public virtual DbSet<WeekType> WeekTypes { get; set; }
        public virtual DbSet<z_Temp_HGPay> z_Temp_HGPay { get; set; }
        public virtual DbSet<z_Temp_HGPayGifts> z_Temp_HGPayGifts { get; set; }
        public virtual DbSet<z_Temp_HGPayInvoice> z_Temp_HGPayInvoice { get; set; }
        public virtual DbSet<CustomersOrderBackup2013> CustomersOrderBackup2013 { get; set; }
        public virtual DbSet<EVourchersCoupon_Log> EVourchersCoupon_Log { get; set; }
        public virtual DbSet<ExchangeLimit> ExchangeLimits { get; set; }
        public virtual DbSet<MealCoupon_Log> MealCoupon_Log { get; set; }
        public virtual DbSet<OrderCoupon> OrderCoupons { get; set; }
        public virtual DbSet<SystemMailTarget> SystemMailTargets { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
        public virtual DbSet<Vourcher> Vourchers { get; set; }
    }
}
