//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HGRecord_Log
    {
        public long Id { get; set; }
        public string MallId { get; set; }
        public string MemberId { get; set; }
        public string Type { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceTime { get; set; }
        public string HappyGoCardNo { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string DepartmentNo { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string GiveTime { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<long> HGMId { get; set; }
        public string LimitActivityNo { get; set; }
    }
}
