//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealCoupon_Log
    {
        public int MCId { get; set; }
        public int MemberId { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public int MallId { get; set; }
        public string DepartmentNo { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RecordKey { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreatDate { get; set; }
        public string CreatFrom { get; set; }
    
        public virtual MealCoupon MealCoupon { get; set; }
    }
}
